services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=openvsx
      - POSTGRES_PASSWORD=openvsx
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    profiles:
      - db
      - debug

  elasticsearch:
    image: elasticsearch:8.7.1
    environment:
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - cluster.routing.allocation.disk.threshold_enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: curl -s http://elasticsearch01:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 50
      start_period: 5s
    profiles:
      - es
      - debug

  kibana:
    image: kibana:8.7.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    profiles:
      - kibana

  redis-node-1:
    image: redis:7.2
    container_name: redis-node-1
    ports:
      - "7001:7000"
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis.conf:/etc/redis.conf
      - /redis/node-1:/data
    environment:
      - REDISCLI_AUTH=openvsx
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7000", "--user", "openvsx", "ping"]
      interval: 5s
      retries: 5
    profiles:
      - redis

  redis-node-2:
    image: redis:7.2
    container_name: redis-node-2
    depends_on:
      redis-node-1:
        condition: service_healthy
    ports:
      - "7002:7000"
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis.conf:/etc/redis.conf
      - /redis/node-2:/data
    environment:
      - REDISCLI_AUTH=openvsx
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7000", "--user", "openvsx", "ping"]
      interval: 5s
      retries: 5
    profiles:
      - redis

  redis-node-3:
    image: redis:7.2
    container_name: redis-node-3
    depends_on:
      redis-node-2:
        condition: service_healthy
    ports:
      - "7003:7000"
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis.conf:/etc/redis.conf
      - /redis/node-3:/data
    environment:
      - REDISCLI_AUTH=openvsx
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7000", "--user", "openvsx", "ping"]
      interval: 5s
      retries: 5
    profiles:
      - redis

  redis-node-4:
    image: redis:7.2
    container_name: redis-node-4
    depends_on:
      redis-node-3:
        condition: service_healthy
    ports:
      - "7004:7000"
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis.conf:/etc/redis.conf
      - /redis/node-4:/data
    environment:
      - REDISCLI_AUTH=openvsx
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7000", "--user", "openvsx", "ping"]
      interval: 5s
      retries: 5
    profiles:
      - redis

  redis-node-5:
    image: redis:7.2
    container_name: redis-node-5
    depends_on:
      redis-node-4:
        condition: service_healthy
    ports:
      - "7005:7000"
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis.conf:/etc/redis.conf
      - /redis/node-5:/data
    environment:
      - REDISCLI_AUTH=openvsx
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7000", "--user", "openvsx", "ping"]
      interval: 5s
      retries: 5
    profiles:
      - redis

  redis-node-6:
    image: redis:7.2
    container_name: redis-node-6
    depends_on:
      redis-node-5:
        condition: service_healthy
    ports:
      - "7006:7000"
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis.conf:/etc/redis.conf
      - /redis/node-6:/data
    environment:
      - REDISCLI_AUTH=openvsx
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7000", "--user", "openvsx", "ping"]
      interval: 5s
      retries: 5
    profiles:
      - redis

  redis-cluster-init:
    image: redis:7.2
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    environment:
      - REDISCLI_AUTH=openvsx
    entrypoint: >
      bash -c "
      sleep 10;
      echo yes | redis-cli --user openvsx --cluster create 
      redis-node-1:7000 redis-node-2:7000 redis-node-3:7000 
      redis-node-4:7000 redis-node-5:7000 redis-node-6:7000 
      --cluster-replicas 1"
    profiles:
      - redis

  redisinsight:
    image: redis/redisinsight
    ports:
      - '5540:5540'
    profiles:
      - redisinsight

  server:
    image: openjdk:17
    working_dir: /app
    command: sh -c 'scripts/generate-properties.sh --docker && ./gradlew assemble && ./gradlew runServer'
    volumes:
      - ./server:/app
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - elasticsearch
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 50
      start_period: 5s
    profiles:
      - openvsx
      - backend
    
  webui:
    image: node:18
    working_dir: /app
    command: sh -c 'yarn && yarn build && yarn build:default && yarn watch & yarn watch:default & yarn start:default'
    volumes:
      - ./webui:/app
    ports:
      - 3000:3000
    depends_on:
      - server
    profiles:
      - openvsx
      - frontend

  cli:
    image: node:18
    working_dir: /app
    command: sh -c 'yarn && yarn watch'
    volumes:
      - ./cli:/app
    depends_on:
      - server
    environment:
      - OVSX_REGISTRY_URL=http://server:8080
    profiles:
      - openvsx
      - commandline
